displayName=Tempoross Wave Timer
author=Marius
description=Sets a timer for the colossal wave in Tempoross
tags=timer,wave,tempoross,fishing
version=1.0.0
plugins=com.temporosswavetimer.TemporossWaveTimerPlugin
build=standard